### ISSUE TITLE
temperature out of range causes get temperature function to return a potentially valid value

### ISSUE THREAD

**Issue by nickmcgill** [MGough/sensorhub#6]
Hi,
Firstly, thank you for an excellent library.

Unless I've misread it, it looks as if a "temperature out of range" error will cause the corresponding "get temperature" to return -1 which can easily be a valid temperature.
It might be better to return a really unlikely value (-273?) instead.

Nick

**Comment by MGough** [comment]
Hah very true! I'd just been using my temperature sensor indoors to try to identify if our flat was getting hot at night despite the boiler being off (turns out it was regularly, think a neighbour had their heating on a weird timer).

I'll take a look at this and see about either throwing an exception or returning maxint. I can probably make it configurable in case handling exceptions isn't desirable.

**Comment by MGough** [comment]
This _should_ now be released and working as 2.0.3 on Pypi, just published it in a different way compared to the other version hence the slight uncertainty there. Let me know if there's any other issues!

**Comment by nickmcgill** [comment]
pip successfully upgraded sensorhub to 2.0.3

No issues to report.

Thank you.
